// LOCAL DEVELOPMENT CONFIG
// This file is for local testing only
// In production, this file is auto-generated by scripts/inject-env.js during build

window.ENV = {
  SUPABASE_URL: 'https://your-project.supabase.co',
  SUPABASE_ANON_KEY: 'your-anon-key-here',
  STRIPE_PUBLISHABLE_KEY: 'pk_test_your_test_key_here'
};

console.log('⚠️  Using LOCAL development config');
console.log('⚠️  Set real values in Netlify environment variables for production');
