window.ENV = {
  SUPABASE_URL=https://qdnijmpcedgrpalnlojp.supabase.co
  SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkbmlqbXBjZWRncnBhbG5sb2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3MTE2NDgsImV4cCI6MjA4NDI4NzY0OH0.3MXwffoZRvDBGLUCBrKSfy0F-O5ZCtMk-tSWyvFMpNo
  STRIPE_PUBLISHABLE_KEY=pk_live_51SaXyvIJONruX42X6gc4a2L1FRCEUycuuig8t4UJkXLW0hHqclY2zVtiyzciykV2LrgqfHALfG1GmSU8cMEicXvE00U56g4NbI
};

console.log('✅ Local Environment Loaded');